title = "STB Educa"
languageCode = "pt-BR"
baseurl = "http://www.stbeduca.com.br"

canonifyurls = true
paginate = 10
copyright = "STB Educa 2017"
# googleAnalytics = "UA-123-45" # delete or comment to disable Google Analytics JS generation
# disqusShortname = "YourDisqusShortname" #delete or comment to disable Disqus comments

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Cursos em engenharia florestal"
  email = "contato@stbeduca.com.br" #Remove this line if you would prefer not to use an email button in the footer.
  postSummariesFrontPage = 4 #Number of post summaries to show on front page, comment out to allow default(4)
  showReadTime = false #set to false to exclude read time from header of post

[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/stbflorestal"
