theme = "current"
title = "STB Educa"
languageCode = "pt-BR"
baseurl = "http://www.stbeduca.com.br"

canonifyurls = true
paginate = 10
copyright = "STB Educa 2017"
# googleAnalytics = "UA-123-45" # delete or comment to disable Google Analytics JS generation
# disqusShortname = "YourDisqusShortname" #delete or comment to disable Disqus comments

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Cursos na área florestal"
  email = "contato@stbeduca.com.br"
  postSummariesFrontPage = 4
  showReadTime = false

[[params.social]]
  title = "facebook"
  url = "https://www.facebook.com/stbflorestal"
